---
language: python
python: "3.9"

addons:
  apt:
    packages:
    - python3-pip

install:
  - pip install ansible molecule docker molecule-docker

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - molecule test