---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Check Java version
    ansible.builtin.shell: . /etc/profile; java -version
    register: java_version

  - ansible.builtin.assert: 
      that:
        - java_version